# Site settings
title: dfdrdodm95 블로그 
url: "https://dfdrdodm95.github.io"
baseurl: ""
description: >
    dfdrdodm95 블로그

# My information
email: dfdrdodm95@gmail.com
author: dfdrdodm95
profile: 
twitter_username: dfdrdodm95
github_username: dfdrdodm95
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: dfdrdodm95/dfdrdodm95.github.io
  repo_id: R_kgDOLanuKg
  category: Announcements
  category_id: DIC_kwDOLanuKs4CepH2

google_analytics:
  ua: SAMPLE-VALUE
  encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/dfdrdodm95/dfdrdodm95.github.io/blame/master/_wiki"
edit: "https://github.com/dfdrdodm95/dfdrdodm95.github.io/edit/master/_wiki"
issue: "https://github.com/dfdrdodm95/dfdrdodm95.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
